name: mayna_system
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^5.0.4
  flutter_keyboard_visibility: ^5.4.1
  dio: ^5.3.3
  flutter_dotenv: ^5.1.0
  flutter_telegram_web_app: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
