services:
  account:
    build:
        context: server/account
        dockerfile: Dockerfile
    restart: unless-stopped
    labels:
      - traefik.http.routers.account.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/account`)
      - traefik.http.routers.account.entrypoints=https
      - traefik.http.routers.account.tls=true
      - traefik.http.routers.account.tls.certresolver=${CERT_RESOLVER}