name: Deploy to dev
run-name: Deploy by @${{ github.actor }}
on: 
  workflow_dispatch:
  push:
      tags:  
        - 'v[0-9]+.[0-9]+.[0-9]+.beta-[0-9]+'


jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: create env file
              run: |
                touch .env
                echo DOMAIN=${{ secrets.DOMAIN }} >> .env
                echo EMAIL=${{ secrets.EMAIL }} >> .env
                echo CERT_RESOLVER=${{ secrets.CERT_RESOLVER }} >> .env
                echo TRAEFIK_USER=${{ secrets.TRAEFIK_USER }} >> .env
                echo TRAEFIK_PASSWORD_HASH=${{ secrets.TRAEFIK_PASSWORD_HASH }} >> .env
                echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
                echo LOG_DEVELOPMENT=${{ secrets.LOG_DEVELOPMENT }} >> .env
                echo LOG_LEVEL=${{ secrets.LOG_LEVEL }} >> .env
                echo LOG_ENCODING=${{ secrets.LOG_ENCODING }} >> .env
                echo LOG_DISABLE_STACKTRACE=${{ secrets.LOG_DISABLE_STACKTRACE }} >> .env
                echo LOG_DISABLE_CALLER=${{ secrets.LOG_DISABLE_CALLER }} >> .env
                echo COMPOSE_FILE="docker-compose.yml:services/traefik/docker-compose.yml:server/account/docker-compose.yml:server/telegram-bot/docker-compose.yml:client/web/docker-compose.yml" >> .env
                cat .env

            - name: docker compose build
              run: docker compose build

            - name: deploy app
              run: docker compose up -d
